// AUTO-GENERATED by scripts/generate_nodes.py from ../core/skills.yaml — do not edit by hand.
import type {
	IExecuteFunctions,
	INodeExecutionData,
	INodeType,
	INodeTypeDescription,
} from 'n8n-workflow';
import { NodeOperationError } from 'n8n-workflow';

import { runSkill, type SkillSpec, type IflyCredentials } from '../shared/run';

const SPEC: SkillSpec = {
	toolName: "proofread",
	script: "skills/iflytek-text-proofread/scripts/text_proofread.py",
	credProfile: "ifly",
	output: "stdout_text",
	args: [
		{ name: "text", type: "string" },
		{ name: "file", type: "string", flag: "--file" },
		{ name: "raw", type: "boolean", flag: "--raw" },
	],
};

export class Proofread implements INodeType {
	description: INodeTypeDescription = {
		displayName: 'iFLYTEK Proofread',
		name: 'proofread',
		icon: 'file:ifly.svg',
		group: ['transform'],
		version: 1,
		description: 'Chinese official-document proofreading and error correction.',
		defaults: { name: 'iFLYTEK Proofread' },
		inputs: ['main'],
		outputs: ['main'],
		credentials: [{ name: 'iflyApi', required: true }],
		properties: [
			{ displayName: 'Text', name: 'text', type: 'string', default: "", description: 'Text to proofread. Provide either text or file.' },
			{ displayName: 'File', name: 'file', type: 'string', default: "", description: 'Path to a UTF-8 text file to proofread instead of inline text.' },
			{ displayName: 'Raw', name: 'raw', type: 'boolean', default: false, description: 'Return the raw (decoded) JSON API response.' },
		],
	};

	async execute(this: IExecuteFunctions): Promise<INodeExecutionData[][]> {
		const items = this.getInputData();
		const creds = (await this.getCredentials('iflyApi')) as unknown as IflyCredentials;
		const out: INodeExecutionData[] = [];
		for (let i = 0; i < items.length; i++) {
			const params: Record<string, unknown> = {};
			params["text"] = this.getNodeParameter("text", i, "");
			params["file"] = this.getNodeParameter("file", i, "");
			params["raw"] = this.getNodeParameter("raw", i, false);
			const res = await runSkill(SPEC, params, creds);
			if (!res.ok) {
				throw new NodeOperationError(this.getNode(), res.stderr || `exit ${res.code}`);
			}
			out.push({ json: { stdout: res.stdout, artifactPath: res.artifactPath ?? null } });
		}
		return [out];
	}
}
