// AUTO-GENERATED by scripts/generate_nodes.py from ../core/skills.yaml — do not edit by hand.
import type {
	IExecuteFunctions,
	INodeExecutionData,
	INodeType,
	INodeTypeDescription,
} from 'n8n-workflow';
import { NodeOperationError } from 'n8n-workflow';

import { runSkill, type SkillSpec, type IflyCredentials } from '../shared/run';

const SPEC: SkillSpec = {
	toolName: "pdf_ocr",
	script: "skills/iflytek-pdf-image-ocr/scripts/pdf_ocr.py",
	credProfile: "ifly",
	output: "async_task",
	args: [
		{ name: "pdf_path", type: "string" },
		{ name: "pdf_url", type: "string", flag: "--pdf-url" },
		{ name: "format", type: "enum", flag: "--format" },
	],
};

export class PdfOcr implements INodeType {
	description: INodeTypeDescription = {
		displayName: 'iFLYTEK Pdf Ocr',
		name: 'pdfOcr',
		icon: 'file:ifly.svg',
		group: ['transform'],
		version: 1,
		description: 'OCR a PDF document into Word, Markdown, or JSON (long-running, polls).',
		defaults: { name: 'iFLYTEK Pdf Ocr' },
		inputs: ['main'],
		outputs: ['main'],
		credentials: [{ name: 'iflyApi', required: true }],
		properties: [
			{ displayName: 'Pdf Path', name: 'pdf_path', type: 'string', default: "", description: 'Path to the PDF file (or use pdf_url).' },
			{ displayName: 'Pdf Url', name: 'pdf_url', type: 'string', default: "", description: 'Public URL of the PDF (alternative to uploading a file).' },
			{ displayName: 'Format', name: 'format', type: 'options', options: [{ name: "word", value: "word" }, { name: "markdown", value: "markdown" }, { name: "json", value: "json" }], default: "markdown", description: 'Output format. Default: markdown.' },
		],
	};

	async execute(this: IExecuteFunctions): Promise<INodeExecutionData[][]> {
		const items = this.getInputData();
		const creds = (await this.getCredentials('iflyApi')) as unknown as IflyCredentials;
		const out: INodeExecutionData[] = [];
		for (let i = 0; i < items.length; i++) {
			const params: Record<string, unknown> = {};
			params["pdf_path"] = this.getNodeParameter("pdf_path", i, "");
			params["pdf_url"] = this.getNodeParameter("pdf_url", i, "");
			params["format"] = this.getNodeParameter("format", i, "markdown");
			const res = await runSkill(SPEC, params, creds);
			if (!res.ok) {
				throw new NodeOperationError(this.getNode(), res.stderr || `exit ${res.code}`);
			}
			out.push({ json: { stdout: res.stdout, artifactPath: res.artifactPath ?? null } });
		}
		return [out];
	}
}
