// AUTO-GENERATED by scripts/generate_nodes.py from ../core/skills.yaml — do not edit by hand.
import type {
	IExecuteFunctions,
	INodeExecutionData,
	INodeType,
	INodeTypeDescription,
} from 'n8n-workflow';
import { NodeOperationError } from 'n8n-workflow';

import { runSkill, type SkillSpec, type IflyCredentials } from '../shared/run';

const SPEC: SkillSpec = {
	toolName: "translate",
	script: "skills/iflytek-translate/scripts/translate.py",
	credProfile: "xfyun",
	output: "stdout_text",
	args: [
		{ name: "text", type: "string" },
		{ name: "file", type: "string", flag: "--file" },
		{ name: "from_lang", type: "string", flag: "--from" },
		{ name: "to_lang", type: "string", flag: "--to" },
		{ name: "raw", type: "boolean", flag: "--raw" },
	],
};

export class Translate implements INodeType {
	description: INodeTypeDescription = {
		displayName: 'iFLYTEK Translate',
		name: 'translate',
		icon: 'file:ifly.svg',
		group: ['transform'],
		version: 1,
		description: 'Machine translation between languages via iFLYTEK.',
		defaults: { name: 'iFLYTEK Translate' },
		inputs: ['main'],
		outputs: ['main'],
		credentials: [{ name: 'iflyApi', required: true }],
		properties: [
			{ displayName: 'Text', name: 'text', type: 'string', default: "", description: 'Text to translate. Provide either text or file.' },
			{ displayName: 'File', name: 'file', type: 'string', default: "", description: 'Path to a UTF-8 text file to translate instead of inline text.' },
			{ displayName: 'From Lang', name: 'from_lang', type: 'string', default: "cn", description: 'Source language code (e.g. cn, en). Default: cn.' },
			{ displayName: 'To Lang', name: 'to_lang', type: 'string', default: "en", description: 'Target language code (e.g. en, cn, ja). Default: en.' },
			{ displayName: 'Raw', name: 'raw', type: 'boolean', default: false, description: 'Return the raw JSON API response.' },
		],
	};

	async execute(this: IExecuteFunctions): Promise<INodeExecutionData[][]> {
		const items = this.getInputData();
		const creds = (await this.getCredentials('iflyApi')) as unknown as IflyCredentials;
		const out: INodeExecutionData[] = [];
		for (let i = 0; i < items.length; i++) {
			const params: Record<string, unknown> = {};
			params["text"] = this.getNodeParameter("text", i, "");
			params["file"] = this.getNodeParameter("file", i, "");
			params["from_lang"] = this.getNodeParameter("from_lang", i, "cn");
			params["to_lang"] = this.getNodeParameter("to_lang", i, "en");
			params["raw"] = this.getNodeParameter("raw", i, false);
			const res = await runSkill(SPEC, params, creds);
			if (!res.ok) {
				throw new NodeOperationError(this.getNode(), res.stderr || `exit ${res.code}`);
			}
			out.push({ json: { stdout: res.stdout, artifactPath: res.artifactPath ?? null } });
		}
		return [out];
	}
}
