#!/usr/bin/env python3
"""Generate one n8n node per skill from core/skills.yaml.

Each generated node embeds a self-contained SkillSpec (so the package needs no
YAML at runtime) and exposes n8n properties derived from the skill's arguments.
Run from the package root:

    python scripts/generate_nodes.py

Also rewrites the `n8n.nodes` list in package.json and drops a shared icon into
each node folder.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import yaml

PKG_ROOT = Path(__file__).resolve().parent.parent
MANIFEST = PKG_ROOT.parent / "core" / "skills.yaml"
NODES_DIR = PKG_ROOT / "nodes"

ICON = (
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">'
    '<rect width="64" height="64" rx="12" fill="#0a5cff"/>'
    '<text x="32" y="42" font-size="30" fill="#fff" text-anchor="middle" '
    'font-family="Arial, sans-serif" font-weight="bold">讯</text></svg>'
)


def pascal(tool_name: str) -> str:
    return "".join(w.capitalize() for w in tool_name.split("_"))


def title(tool_name: str) -> str:
    return " ".join(w.capitalize() for w in tool_name.split("_"))


def camel(tool_name: str) -> str:
    p = pascal(tool_name)
    return p[0].lower() + p[1:]


def ts_lit(value) -> str:
    return json.dumps(value, ensure_ascii=False)


def spec_object(skill: dict) -> str:
    args = []
    for a in skill.get("args", []):
        parts = [f"name: {ts_lit(a['name'])}", f"type: {ts_lit(a.get('type', 'string'))}"]
        if a.get("flag"):
            parts.append(f"flag: {ts_lit(a['flag'])}")
        if a.get("is_output_path"):
            parts.append("isOutputPath: true")
        args.append("{ " + ", ".join(parts) + " }")
    entry = skill["entry"]
    lines = [
        f"\ttoolName: {ts_lit(skill['tool_name'])},",
        f"\tscript: {ts_lit(entry['script'])},",
    ]
    if entry.get("subcommand"):
        lines.append(f"\tsubcommand: {ts_lit(entry['subcommand'])},")
    lines.append(f"\tcredProfile: {ts_lit(skill.get('cred_profile', 'none'))},")
    lines.append(f"\toutput: {ts_lit(skill.get('output', 'stdout_text'))},")
    lines.append("\targs: [\n\t\t" + ",\n\t\t".join(args) + ",\n\t],")
    return "const SPEC: SkillSpec = {\n" + "\n".join(lines) + "\n};"


def property_block(arg: dict) -> str:
    name = arg["name"]
    display = name.replace("_", " ").title()
    desc = arg.get("description", "").replace("\\", "\\\\").replace("'", "\\'")
    default = arg.get("default")
    required = arg.get("required", False)
    typ = arg.get("type", "string")

    fields = [
        f"displayName: '{display}'",
        f"name: '{name}'",
    ]
    if typ == "boolean":
        fields.append("type: 'boolean'")
        fields.append(f"default: {ts_lit(bool(default))}")
    elif typ in ("integer", "number"):
        fields.append("type: 'number'")
        fields.append(f"default: {ts_lit(default if default is not None else 0)}")
    elif typ == "enum":
        opts = ", ".join(
            "{ name: %s, value: %s }" % (ts_lit(str(v)), ts_lit(v)) for v in arg.get("enum", [])
        )
        fields.append("type: 'options'")
        fields.append(f"options: [{opts}]")
        fields.append(f"default: {ts_lit(default if default is not None else (arg.get('enum') or [''])[0])}")
    else:
        fields.append("type: 'string'")
        fields.append(f"default: {ts_lit(default if default is not None else '')}")
    if required:
        fields.append("required: true")
    if desc:
        fields.append(f"description: '{desc}'")
    return "\t\t\t{ " + ", ".join(fields) + " }"


def node_source(skill: dict) -> str:
    cls = pascal(skill["tool_name"])
    name = camel(skill["tool_name"])
    disp = f"iFLYTEK {title(skill['tool_name'])}"
    summary = skill["summary"].replace("'", "\\'")

    visible_args = [a for a in skill.get("args", []) if not a.get("is_output_path")]
    properties = ",\n".join(property_block(a) for a in visible_args)

    param_reads = []
    for a in visible_args:
        default = a.get("default")
        if a.get("type") == "boolean":
            d = "false"
        elif a.get("type") in ("integer", "number"):
            d = ts_lit(default if default is not None else 0)
        else:
            d = ts_lit(default if default is not None else "")
        param_reads.append(
            f"\t\t\tparams[{ts_lit(a['name'])}] = this.getNodeParameter({ts_lit(a['name'])}, i, {d});"
        )
    reads = "\n".join(param_reads)

    return f"""// AUTO-GENERATED by scripts/generate_nodes.py from ../core/skills.yaml — do not edit by hand.
import type {{
\tIExecuteFunctions,
\tINodeExecutionData,
\tINodeType,
\tINodeTypeDescription,
}} from 'n8n-workflow';
import {{ NodeOperationError }} from 'n8n-workflow';

import {{ runSkill, type SkillSpec, type IflyCredentials }} from '../shared/run';

{spec_object(skill)}

export class {cls} implements INodeType {{
\tdescription: INodeTypeDescription = {{
\t\tdisplayName: '{disp}',
\t\tname: '{name}',
\t\ticon: 'file:ifly.svg',
\t\tgroup: ['transform'],
\t\tversion: 1,
\t\tdescription: '{summary}',
\t\tdefaults: {{ name: '{disp}' }},
\t\tinputs: ['main'],
\t\toutputs: ['main'],
\t\tcredentials: [{{ name: 'iflyApi', required: true }}],
\t\tproperties: [
{properties},
\t\t],
\t}};

\tasync execute(this: IExecuteFunctions): Promise<INodeExecutionData[][]> {{
\t\tconst items = this.getInputData();
\t\tconst creds = (await this.getCredentials('iflyApi')) as unknown as IflyCredentials;
\t\tconst out: INodeExecutionData[] = [];
\t\tfor (let i = 0; i < items.length; i++) {{
\t\t\tconst params: Record<string, unknown> = {{}};
{reads}
\t\t\tconst res = await runSkill(SPEC, params, creds);
\t\t\tif (!res.ok) {{
\t\t\t\tthrow new NodeOperationError(this.getNode(), res.stderr || `exit ${{res.code}}`);
\t\t\t}}
\t\t\tout.push({{ json: {{ stdout: res.stdout, artifactPath: res.artifactPath ?? null }} }});
\t\t}}
\t\treturn [out];
\t}}
}}
"""


def main() -> None:
    data = yaml.safe_load(MANIFEST.read_text(encoding="utf-8"))
    node_paths = []
    for skill in data["skills"]:
        cls = pascal(skill["tool_name"])
        node_dir = NODES_DIR / cls
        node_dir.mkdir(parents=True, exist_ok=True)
        (node_dir / f"{cls}.node.ts").write_text(node_source(skill), encoding="utf-8")
        (node_dir / "ifly.svg").write_text(ICON, encoding="utf-8")
        node_paths.append(f"dist/nodes/{cls}/{cls}.node.js")
        print(f"generated nodes/{cls}/{cls}.node.ts")

    # Sync package.json n8n.nodes list.
    pkg_path = PKG_ROOT / "package.json"
    pkg = json.loads(pkg_path.read_text(encoding="utf-8"))
    pkg["n8n"] = {
        "n8nNodesApiVersion": 1,
        "credentials": ["dist/credentials/IflyApi.credentials.js"],
        "nodes": node_paths,
    }
    pkg_path.write_text(json.dumps(pkg, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"\nupdated {pkg_path} with {len(node_paths)} nodes")


if __name__ == "__main__":
    main()
