// AUTO-GENERATED by scripts/generate_nodes.py from ../core/skills.yaml — do not edit by hand.
import type {
	IExecuteFunctions,
	INodeExecutionData,
	INodeType,
	INodeTypeDescription,
} from 'n8n-workflow';
import { NodeOperationError } from 'n8n-workflow';

import { runSkill, type SkillSpec, type IflyCredentials } from '../shared/run';

const SPEC: SkillSpec = {
	toolName: "video_translate",
	script: "skills/iflytek-video-translate/scripts/xfei_video_translate.py",
	credProfile: "xfyun",
	output: "async_task",
	args: [
		{ name: "action", type: "enum", flag: "--action" },
		{ name: "file_url", type: "string", flag: "--file_url" },
		{ name: "src_lang", type: "string", flag: "--src_lang" },
		{ name: "dest_lang", type: "string", flag: "--dest_lang" },
		{ name: "task_id", type: "string", flag: "--task_id" },
	],
};

export class VideoTranslate implements INodeType {
	description: INodeTypeDescription = {
		displayName: 'iFLYTEK Video Translate',
		name: 'videoTranslate',
		icon: 'file:ifly.svg',
		group: ['transform'],
		version: 1,
		description: 'Translate the spoken content of a video (multi-action, async).',
		defaults: { name: 'iFLYTEK Video Translate' },
		inputs: ['main'],
		outputs: ['main'],
		credentials: [{ name: 'iflyApi', required: true }],
		properties: [
			{ displayName: 'Action', name: 'action', type: 'options', options: [{ name: "create_task", value: "create_task" }, { name: "get_task", value: "get_task" }, { name: "confirm_transcript", value: "confirm_transcript" }], default: "create_task", required: true, description: 'Workflow action to perform.' },
			{ displayName: 'File Url', name: 'file_url', type: 'string', default: "", description: 'Video file OSS URL (required for create_task).' },
			{ displayName: 'Src Lang', name: 'src_lang', type: 'string', default: "en", description: 'Source language. Default: en.' },
			{ displayName: 'Dest Lang', name: 'dest_lang', type: 'string', default: "zh", description: 'Target language. Default: zh.' },
			{ displayName: 'Task Id', name: 'task_id', type: 'string', default: "", description: 'Task ID (required for get_task / confirm_transcript).' },
		],
	};

	async execute(this: IExecuteFunctions): Promise<INodeExecutionData[][]> {
		const items = this.getInputData();
		const creds = (await this.getCredentials('iflyApi')) as unknown as IflyCredentials;
		const out: INodeExecutionData[] = [];
		for (let i = 0; i < items.length; i++) {
			const params: Record<string, unknown> = {};
			params["action"] = this.getNodeParameter("action", i, "");
			params["file_url"] = this.getNodeParameter("file_url", i, "");
			params["src_lang"] = this.getNodeParameter("src_lang", i, "en");
			params["dest_lang"] = this.getNodeParameter("dest_lang", i, "zh");
			params["task_id"] = this.getNodeParameter("task_id", i, "");
			const res = await runSkill(SPEC, params, creds);
			if (!res.ok) {
				throw new NodeOperationError(this.getNode(), res.stderr || `exit ${res.code}`);
			}
			out.push({ json: { stdout: res.stdout, artifactPath: res.artifactPath ?? null } });
		}
		return [out];
	}
}
