// AUTO-GENERATED by scripts/generate_nodes.py from ../core/skills.yaml — do not edit by hand.
import type {
	IExecuteFunctions,
	INodeExecutionData,
	INodeType,
	INodeTypeDescription,
} from 'n8n-workflow';
import { NodeOperationError } from 'n8n-workflow';

import { runSkill, type SkillSpec, type IflyCredentials } from '../shared/run';

const SPEC: SkillSpec = {
	toolName: "image_understanding",
	script: "skills/iflytek-image-understanding/scripts/image_understanding.py",
	credProfile: "ifly",
	output: "stdout_text",
	args: [
		{ name: "image", type: "string" },
		{ name: "question", type: "string", flag: "--question" },
		{ name: "domain", type: "enum", flag: "--domain" },
		{ name: "temperature", type: "number", flag: "--temperature" },
		{ name: "max_tokens", type: "integer", flag: "--max-tokens" },
	],
};

export class ImageUnderstanding implements INodeType {
	description: INodeTypeDescription = {
		displayName: 'iFLYTEK Image Understanding',
		name: 'imageUnderstanding',
		icon: 'file:ifly.svg',
		group: ['transform'],
		version: 1,
		description: 'Multimodal image understanding — describe or answer questions about an image.',
		defaults: { name: 'iFLYTEK Image Understanding' },
		inputs: ['main'],
		outputs: ['main'],
		credentials: [{ name: 'iflyApi', required: true }],
		properties: [
			{ displayName: 'Image', name: 'image', type: 'string', default: "", required: true, description: 'Path to the image file (.jpg, .jpeg, .png).' },
			{ displayName: 'Question', name: 'question', type: 'string', default: "请详细描述这张图片的内容", description: 'Question to ask about the image.' },
			{ displayName: 'Domain', name: 'domain', type: 'options', options: [{ name: "general", value: "general" }, { name: "imagev3", value: "imagev3" }], default: "imagev3", description: 'Model version. Default: imagev3.' },
			{ displayName: 'Temperature', name: 'temperature', type: 'number', default: 0.5, description: 'Sampling temperature (0, 1]. Default: 0.5.' },
			{ displayName: 'Max Tokens', name: 'max_tokens', type: 'number', default: 2048, description: 'Max response tokens (1-8192). Default: 2048.' },
		],
	};

	async execute(this: IExecuteFunctions): Promise<INodeExecutionData[][]> {
		const items = this.getInputData();
		const creds = (await this.getCredentials('iflyApi')) as unknown as IflyCredentials;
		const out: INodeExecutionData[] = [];
		for (let i = 0; i < items.length; i++) {
			const params: Record<string, unknown> = {};
			params["image"] = this.getNodeParameter("image", i, "");
			params["question"] = this.getNodeParameter("question", i, "请详细描述这张图片的内容");
			params["domain"] = this.getNodeParameter("domain", i, "imagev3");
			params["temperature"] = this.getNodeParameter("temperature", i, 0.5);
			params["max_tokens"] = this.getNodeParameter("max_tokens", i, 2048);
			const res = await runSkill(SPEC, params, creds);
			if (!res.ok) {
				throw new NodeOperationError(this.getNode(), res.stderr || `exit ${res.code}`);
			}
			out.push({ json: { stdout: res.stdout, artifactPath: res.artifactPath ?? null } });
		}
		return [out];
	}
}
