// AUTO-GENERATED by scripts/generate_nodes.py from ../core/skills.yaml — do not edit by hand.
import type {
	IExecuteFunctions,
	INodeExecutionData,
	INodeType,
	INodeTypeDescription,
} from 'n8n-workflow';
import { NodeOperationError } from 'n8n-workflow';

import { runSkill, type SkillSpec, type IflyCredentials } from '../shared/run';

const SPEC: SkillSpec = {
	toolName: "hyper_tts",
	script: "skills/iflytek-hyper-tts/scripts/xfei_hyper_tts.py",
	credProfile: "xfei",
	output: "file",
	args: [
		{ name: "action", type: "enum", flag: "--action" },
		{ name: "text", type: "string", flag: "--text" },
		{ name: "output", type: "string", flag: "--output", isOutputPath: true },
		{ name: "vcn", type: "string", flag: "--vcn" },
		{ name: "speed", type: "integer", flag: "--speed" },
		{ name: "volume", type: "integer", flag: "--volume" },
		{ name: "pitch", type: "integer", flag: "--pitch" },
		{ name: "sample_rate", type: "enum", flag: "--sample_rate" },
		{ name: "role", type: "string", flag: "--role" },
	],
};

export class HyperTts implements INodeType {
	description: INodeTypeDescription = {
		displayName: 'iFLYTEK Hyper Tts',
		name: 'hyperTts',
		icon: 'file:ifly.svg',
		group: ['transform'],
		version: 1,
		description: 'Ultra-realistic text-to-speech synthesis with voice and prosody control.',
		defaults: { name: 'iFLYTEK Hyper Tts' },
		inputs: ['main'],
		outputs: ['main'],
		credentials: [{ name: 'iflyApi', required: true }],
		properties: [
			{ displayName: 'Action', name: 'action', type: 'options', options: [{ name: "synthesize", value: "synthesize" }, { name: "list_voices", value: "list_voices" }], default: "synthesize", description: 'synthesize audio, or list_voices to enumerate available voices.' },
			{ displayName: 'Text', name: 'text', type: 'string', default: "", description: 'Text to synthesize (required when action=synthesize).' },
			{ displayName: 'Vcn', name: 'vcn', type: 'string', default: "x5_lingxiaotang_flow", description: 'Voice (VCN) code. Default: x5_lingxiaotang_flow (聆小糖, female).' },
			{ displayName: 'Speed', name: 'speed', type: 'number', default: 50, description: 'Speed 0-100 (50 = normal).' },
			{ displayName: 'Volume', name: 'volume', type: 'number', default: 50, description: 'Volume 0-100 (50 = normal).' },
			{ displayName: 'Pitch', name: 'pitch', type: 'number', default: 50, description: 'Pitch 0-100 (50 = normal).' },
			{ displayName: 'Sample Rate', name: 'sample_rate', type: 'options', options: [{ name: "8000", value: 8000 }, { name: "16000", value: 16000 }, { name: "24000", value: 24000 }], default: 24000, description: 'Sample rate in Hz. Default: 24000.' },
			{ displayName: 'Role', name: 'role', type: 'string', default: "", description: 'Optional role for supported voices: chat, narration, customer_service.' },
		],
	};

	async execute(this: IExecuteFunctions): Promise<INodeExecutionData[][]> {
		const items = this.getInputData();
		const creds = (await this.getCredentials('iflyApi')) as unknown as IflyCredentials;
		const out: INodeExecutionData[] = [];
		for (let i = 0; i < items.length; i++) {
			const params: Record<string, unknown> = {};
			params["action"] = this.getNodeParameter("action", i, "synthesize");
			params["text"] = this.getNodeParameter("text", i, "");
			params["vcn"] = this.getNodeParameter("vcn", i, "x5_lingxiaotang_flow");
			params["speed"] = this.getNodeParameter("speed", i, 50);
			params["volume"] = this.getNodeParameter("volume", i, 50);
			params["pitch"] = this.getNodeParameter("pitch", i, 50);
			params["sample_rate"] = this.getNodeParameter("sample_rate", i, 24000);
			params["role"] = this.getNodeParameter("role", i, "");
			const res = await runSkill(SPEC, params, creds);
			if (!res.ok) {
				throw new NodeOperationError(this.getNode(), res.stderr || `exit ${res.code}`);
			}
			out.push({ json: { stdout: res.stdout, artifactPath: res.artifactPath ?? null } });
		}
		return [out];
	}
}
