// AUTO-GENERATED by scripts/generate_nodes.py from ../core/skills.yaml — do not edit by hand.
import type {
	IExecuteFunctions,
	INodeExecutionData,
	INodeType,
	INodeTypeDescription,
} from 'n8n-workflow';
import { NodeOperationError } from 'n8n-workflow';

import { runSkill, type SkillSpec, type IflyCredentials } from '../shared/run';

const SPEC: SkillSpec = {
	toolName: "transcribe",
	script: "skills/iflytek-speed-transcription/scripts/transcribe.py",
	credProfile: "xfei",
	output: "async_task",
	args: [
		{ name: "file_path", type: "string" },
		{ name: "language", type: "string", flag: "--language" },
		{ name: "accent", type: "string", flag: "--accent" },
		{ name: "speaker_num", type: "integer", flag: "--speaker-num" },
		{ name: "output_format", type: "enum", flag: "--output-format" },
	],
};

export class Transcribe implements INodeType {
	description: INodeTypeDescription = {
		displayName: 'iFLYTEK Transcribe',
		name: 'transcribe',
		icon: 'file:ifly.svg',
		group: ['transform'],
		version: 1,
		description: 'High-speed audio-to-text transcription (long-running, polls).',
		defaults: { name: 'iFLYTEK Transcribe' },
		inputs: ['main'],
		outputs: ['main'],
		credentials: [{ name: 'iflyApi', required: true }],
		properties: [
			{ displayName: 'File Path', name: 'file_path', type: 'string', default: "", required: true, description: 'Path to the audio file.' },
			{ displayName: 'Language', name: 'language', type: 'string', default: "zh_cn", description: 'Language code. Default: zh_cn.' },
			{ displayName: 'Accent', name: 'accent', type: 'string', default: "mandarin", description: 'Accent. Default: mandarin.' },
			{ displayName: 'Speaker Num', name: 'speaker_num', type: 'number', default: 0, description: 'Number of speakers for diarization.' },
			{ displayName: 'Output Format', name: 'output_format', type: 'options', options: [{ name: "text", value: "text" }, { name: "json", value: "json" }], default: "text", description: 'Output format. Default: text.' },
		],
	};

	async execute(this: IExecuteFunctions): Promise<INodeExecutionData[][]> {
		const items = this.getInputData();
		const creds = (await this.getCredentials('iflyApi')) as unknown as IflyCredentials;
		const out: INodeExecutionData[] = [];
		for (let i = 0; i < items.length; i++) {
			const params: Record<string, unknown> = {};
			params["file_path"] = this.getNodeParameter("file_path", i, "");
			params["language"] = this.getNodeParameter("language", i, "zh_cn");
			params["accent"] = this.getNodeParameter("accent", i, "mandarin");
			params["speaker_num"] = this.getNodeParameter("speaker_num", i, 0);
			params["output_format"] = this.getNodeParameter("output_format", i, "text");
			const res = await runSkill(SPEC, params, creds);
			if (!res.ok) {
				throw new NodeOperationError(this.getNode(), res.stderr || `exit ${res.code}`);
			}
			out.push({ json: { stdout: res.stdout, artifactPath: res.artifactPath ?? null } });
		}
		return [out];
	}
}
