// AUTO-GENERATED by scripts/generate_nodes.py from ../core/skills.yaml — do not edit by hand.
import type {
	IExecuteFunctions,
	INodeExecutionData,
	INodeType,
	INodeTypeDescription,
} from 'n8n-workflow';
import { NodeOperationError } from 'n8n-workflow';

import { runSkill, type SkillSpec, type IflyCredentials } from '../shared/run';

const SPEC: SkillSpec = {
	toolName: "image_ocr",
	script: "skills/iflytek-pdf-image-ocr/scripts/image_ocr.py",
	credProfile: "ifly",
	output: "stdout_text",
	args: [
		{ name: "image_path", type: "string" },
		{ name: "format", type: "enum", flag: "--format" },
	],
};

export class ImageOcr implements INodeType {
	description: INodeTypeDescription = {
		displayName: 'iFLYTEK Image Ocr',
		name: 'imageOcr',
		icon: 'file:ifly.svg',
		group: ['transform'],
		version: 1,
		description: 'General OCR for a single image, returning text as JSON and/or Markdown.',
		defaults: { name: 'iFLYTEK Image Ocr' },
		inputs: ['main'],
		outputs: ['main'],
		credentials: [{ name: 'iflyApi', required: true }],
		properties: [
			{ displayName: 'Image Path', name: 'image_path', type: 'string', default: "", required: true, description: 'Path to the image file.' },
			{ displayName: 'Format', name: 'format', type: 'options', options: [{ name: "json", value: "json" }, { name: "markdown", value: "markdown" }, { name: "json,markdown", value: "json,markdown" }], default: "markdown", description: 'Output format. Default: markdown.' },
		],
	};

	async execute(this: IExecuteFunctions): Promise<INodeExecutionData[][]> {
		const items = this.getInputData();
		const creds = (await this.getCredentials('iflyApi')) as unknown as IflyCredentials;
		const out: INodeExecutionData[] = [];
		for (let i = 0; i < items.length; i++) {
			const params: Record<string, unknown> = {};
			params["image_path"] = this.getNodeParameter("image_path", i, "");
			params["format"] = this.getNodeParameter("format", i, "markdown");
			const res = await runSkill(SPEC, params, creds);
			if (!res.ok) {
				throw new NodeOperationError(this.getNode(), res.stderr || `exit ${res.code}`);
			}
			out.push({ json: { stdout: res.stdout, artifactPath: res.artifactPath ?? null } });
		}
		return [out];
	}
}
