// AUTO-GENERATED by scripts/generate_nodes.py from ../core/skills.yaml — do not edit by hand.
import type {
	IExecuteFunctions,
	INodeExecutionData,
	INodeType,
	INodeTypeDescription,
} from 'n8n-workflow';
import { NodeOperationError } from 'n8n-workflow';

import { runSkill, type SkillSpec, type IflyCredentials } from '../shared/run';

const SPEC: SkillSpec = {
	toolName: "voiceclone_synth",
	script: "skills/iflytek-voiceclone-tts/scripts/voiceclone.py",
	subcommand: "synth",
	credProfile: "ifly",
	output: "file",
	args: [
		{ name: "text", type: "string" },
		{ name: "res_id", type: "string", flag: "--res-id" },
		{ name: "output", type: "string", flag: "--output", isOutputPath: true },
		{ name: "format", type: "enum", flag: "--format" },
	],
};

export class VoicecloneSynth implements INodeType {
	description: INodeTypeDescription = {
		displayName: 'iFLYTEK Voiceclone Synth',
		name: 'voicecloneSynth',
		icon: 'file:ifly.svg',
		group: ['transform'],
		version: 1,
		description: 'Synthesize speech from a previously trained cloned voice resource.',
		defaults: { name: 'iFLYTEK Voiceclone Synth' },
		inputs: ['main'],
		outputs: ['main'],
		credentials: [{ name: 'iflyApi', required: true }],
		properties: [
			{ displayName: 'Text', name: 'text', type: 'string', default: "", description: 'Text to synthesize (or use file).' },
			{ displayName: 'Res Id', name: 'res_id', type: 'string', default: "", required: true, description: 'Voice resource ID obtained from a completed training task.' },
			{ displayName: 'Format', name: 'format', type: 'options', options: [{ name: "mp3", value: "mp3" }, { name: "pcm", value: "pcm" }, { name: "speex", value: "speex" }, { name: "opus", value: "opus" }], default: "mp3", description: 'Audio format. Default: mp3.' },
		],
	};

	async execute(this: IExecuteFunctions): Promise<INodeExecutionData[][]> {
		const items = this.getInputData();
		const creds = (await this.getCredentials('iflyApi')) as unknown as IflyCredentials;
		const out: INodeExecutionData[] = [];
		for (let i = 0; i < items.length; i++) {
			const params: Record<string, unknown> = {};
			params["text"] = this.getNodeParameter("text", i, "");
			params["res_id"] = this.getNodeParameter("res_id", i, "");
			params["format"] = this.getNodeParameter("format", i, "mp3");
			const res = await runSkill(SPEC, params, creds);
			if (!res.ok) {
				throw new NodeOperationError(this.getNode(), res.stderr || `exit ${res.code}`);
			}
			out.push({ json: { stdout: res.stdout, artifactPath: res.artifactPath ?? null } });
		}
		return [out];
	}
}
