// AUTO-GENERATED by scripts/generate_nodes.py from ../core/skills.yaml — do not edit by hand.
import type {
	IExecuteFunctions,
	INodeExecutionData,
	INodeType,
	INodeTypeDescription,
} from 'n8n-workflow';
import { NodeOperationError } from 'n8n-workflow';

import { runSkill, type SkillSpec, type IflyCredentials } from '../shared/run';

const SPEC: SkillSpec = {
	toolName: "ocr_invoice",
	script: "skills/iflytek-ocr-invoice/scripts/invoice.py",
	credProfile: "xfyun",
	output: "json",
	args: [
		{ name: "image", type: "string" },
		{ name: "raw", type: "boolean", flag: "--raw" },
	],
};

export class OcrInvoice implements INodeType {
	description: INodeTypeDescription = {
		displayName: 'iFLYTEK Ocr Invoice',
		name: 'ocrInvoice',
		icon: 'file:ifly.svg',
		group: ['transform'],
		version: 1,
		description: 'Extract structured fields from an invoice or receipt image.',
		defaults: { name: 'iFLYTEK Ocr Invoice' },
		inputs: ['main'],
		outputs: ['main'],
		credentials: [{ name: 'iflyApi', required: true }],
		properties: [
			{ displayName: 'Image', name: 'image', type: 'string', default: "", required: true, description: 'Path to the invoice/receipt image (png, jpg, bmp, gif, tif, pdf).' },
			{ displayName: 'Raw', name: 'raw', type: 'boolean', default: false, description: 'Return the raw API JSON response.' },
		],
	};

	async execute(this: IExecuteFunctions): Promise<INodeExecutionData[][]> {
		const items = this.getInputData();
		const creds = (await this.getCredentials('iflyApi')) as unknown as IflyCredentials;
		const out: INodeExecutionData[] = [];
		for (let i = 0; i < items.length; i++) {
			const params: Record<string, unknown> = {};
			params["image"] = this.getNodeParameter("image", i, "");
			params["raw"] = this.getNodeParameter("raw", i, false);
			const res = await runSkill(SPEC, params, creds);
			if (!res.ok) {
				throw new NodeOperationError(this.getNode(), res.stderr || `exit ${res.code}`);
			}
			out.push({ json: { stdout: res.stdout, artifactPath: res.artifactPath ?? null } });
		}
		return [out];
	}
}
